### ISSUE TITLE
[공통] 무한 스크롤 기준 높이 재설정

### ISSUE THREAD

**Issue by dar-jeeling** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#127]
# 개요

현재 푸터 끝에 도달해야 무한 스크롤이 작동하고 있으므로, 높이 기준을 재설정합니다.
# 작업 내용

- [ ] 무한 스크롤 기준 높이 재설정

https://stackoverflow.com/questions/45585542/detecting-when-user-scrolls-to-bottom-of-div-with-react-js

**Comment by dar-jeeling** [comment]
무한 스크롤의 경우, 스크롤 이벤트를 이용해서 만들어서 
해당 스크롤에 닿았을 때 패칭이 두 번 씩 일어나는 문제가 있습니다 ㅠㅠ 
제가 짐작하는 이유는 이벤트가 트리거 되는 기준이 scrollTop + clientHeight >= scrollHeight - 제외할 높이 인데, 이렇게 될 경우 1) 처음 스크롤을 내렸을 때 데이터 fetching이 일어나고, 2) 두 번째 스크롤을 내릴 때 한 번 더 데이터 fetching이 일어나기 때문이라고 생각하고 있습니다.
이를 해결하기 위해 무한 스크롤 방식을 **스크롤 이벤트가 아니라 `Intersection Observer`를 사용하는 것**으로 바꿔야 합니다. 

우선 제가 구현해야하는 부분을 먼저 구현한 후, 이 부분 구현을 바꾸도록 하겠습니다.

**Comment by gitul0515** [comment]
흠...스크롤 방식의 고질적 문제라고는 생각되지 않는 것 같습니다. 
스크롤 방식을 고수하면서도 해결할 수 있는 방안이 있지 않을까
조심스럽게 생각해봅니다. 

한편으로는 시간이 부족하므로, Intersection Observer로 빠르게 해결할 수 있다면, 
옵저버를 사용하는 것도 괜찮아 보입니다 :)
