### ISSUE TITLE
[버그] 유저 페이지 및 헤더의 버그 수정

### ISSUE THREAD

**Issue by gitul0515** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#174]
# 개요

배포 시, 유저 페이지 및 헤더에서 발생한 버그를 수정합니다. 

# 작업 내용

- [ ] 유저 페이지 진입이 되지 않는 오류 수정 
- [ ] 로그아웃이 되지 않는 오류 수정 
- [ ] 헤더가 유틸리티 메뉴가 오른쪽으로 쏠리는 오류 수정

**Comment by dar-jeeling** [comment]
로그아웃은 제가 처리하겠습니다! 
백에서 응답데이터가 바뀌어서 전역 상태에서 로직을 일부 수정해야합니다 
나머지 부분 고쳐주세요!!

**Comment by gitul0515** [comment]
네 알겠습니다.
