### ISSUE TITLE
hotfix: 배포시 토큰 저장되지 않는 에러

### ISSUE THREAD

**Issue by dar-jeeling** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#186]
# 개요

# 작업 내용

- [ ]
- [ ]

**Comment by dar-jeeling** [comment]
https://github.com/prgrms-web-devcourse/Team-BackFro-ArtZip-FE/discussions/192

**Comment by punchdrunkard** [comment]
- Recoil의 `effect` 와 RecoilRoot의 initialProps 속성으로 해결 가능
