### ISSUE TITLE
[공통] next image를 사용하기 위한 domain 추가

### ISSUE THREAD

**Issue by dar-jeeling** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#223]
# 개요

이미지 최적화를 위해 next/image 를 사용하기 위하여 domain을 추가합니다.
백엔드 분에게 여쭤봤는데, 도메인이 정해져있는 것 같더라고요!
우선 추가하고 커뮤니티 페이지에 점진적으로 추가해보겠습니다.

# 작업 내용

- [ ] next image를 사용하기 위한 domain 추가
- [ ] 공공 API 에서 사용하는 부분 `http://www.culture.go.kr/ `
- [ ] 데이터 베이스에 저장된 부분 `https://devcourse-backfro-s3.s3.ap-northeast-2.amazonaws.com/`

**Comment by gitul0515** [comment]
@dar-jeeling  다은님, 이 작업 제가 제가 대신 해도 괜찮을까요?
