### ISSUE TITLE
[공통] components 폴더 구조 초기 설정

### ISSUE THREAD

**Issue by gitul0515** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#25]
# 개요

components 폴더 내에 atoms, molecules, organisms, templates 폴더를 생성합니다. 

# 작업 내용
- [ ] atoms, molecules, organisms, templates 폴더 생성
- [ ] 각 폴더에 index.ts 파일 생성

**Comment by Hyevvy** [comment]
@gitul0515 폴더구조 초기설정은 어떠실까요?!?

**Comment by dar-jeeling** [comment]
저도 해삐 말에 공감합니다!! 
컴포넌트 폴더 구조 초기설정<
이라고 할게용

**Comment by Hyevvy** [comment]
감사합니당 🙇🏻‍♀️
