### ISSUE TITLE
[공통] 전체 페이지에 인증 로직 추가

### ISSUE THREAD

**Issue by dar-jeeling** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#254]
# 개요

# 작업 내용

- [ ] iron-session 을 이용하여 토큰을 iron session 에 저장하고 SSR에서도 사용할 수 있게 만들기
- [ ]

**Comment by punchdrunkard** [comment]
라이브러리 안 쓰고 할 수있는 방안을 찾아서 Close
