### ISSUE TITLE
[전시회 상세 페이지] 클립보드 복사 message추가 및 전시회 상세 피드백 반영

### ISSUE THREAD

**Issue by yunjjeongjo** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#261]
# 개요
기동멘토님이 피드백 주셨던 부분 + 기홍님이 말씀해주신 fee 내용 제거 등 리팩토링에 반영할 계획입니다.

# 작업 내용

- [ ] 클립보드 복사 후 성공 message
- [ ] 전시회 description 디자인 수정
- [ ] 아이콘 레이아웃 수정
- [ ] 전시회 정보 fee 제거 및 디자인 수정

**Comment by Hyevvy** [comment]
<img width="259" alt="스크린샷 2022-09-09 오후 7 31 30" src="https://user-images.githubusercontent.com/72402747/189330635-a8126b27-647a-404f-99b0-a101ca1b03a6.png">

그린! 다름이 아니고 제가 메인페이지 반응형을 하려고 다른 페이지를 참고하던 도중에 발견해서 코멘트남겨용 !! 

홈페이지 주소도 말줄임을 이용하면 좋을 거 같아서요 ! 한 번 확인해주시겠어요 ?? 🙂
