### ISSUE TITLE
[커뮤니티 페이지] 시간 함수 버그 수정

### ISSUE THREAD

**Issue by gitul0515** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#288]
# 개요

시간 표시 함수(displayDate)가 제대로 동작하지 않는 것 같습니다. 
방금 작성한 후기인데 '9시간 전'이라고 뜨네요. 

![image](https://user-images.githubusercontent.com/80658269/191477665-706ff502-f7c6-44f0-8563-9ac83660379f.png)

이 버그를 수정해야할 것 같습니다. 

# 작업 내용

- [ ] 시간 표시 함수 버그 수정

**Comment by punchdrunkard** [comment]
전에 db단에서 문제가 생겨서 무조건 n시간 전으로 고정된 적이 있었습니다! 한 번 스웨거에서 확인해보겠어요?

**Comment by gitul0515** [comment]
조언 감사합니다 👍
