### ISSUE TITLE
[전시회 상세 페이지] 전시회 상세 정보  SSR + CSR 로 변경

### ISSUE THREAD

**Issue by yunjjeongjo** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#304]
# 개요
전시회 상세 정보  SSR + CSR 로 변경
# 작업 내용

- [ ]전시회 상세 정보  SSR + CSR 로 변경

**Comment by dar-jeeling** [comment]
요 부분 SSR로만 변경해도 될 것 같습니다!
(SSR 쪽에서 나타나는 버그들 픽스가 가능할 것 같아요!)

**Comment by punchdrunkard** [comment]
SSR에서 데이터를 불러오기 위한 함수가 새로 추가될 것 같습니다!
작업 조금만 보류해주세요!

**Comment by punchdrunkard** [comment]
https://github.com/prgrms-web-devcourse/Team-BackFro-ArtZip-FE/discussions/313

요 discussion 참고해주시길 바랍니다!
CSR 사용하지 않아도, SSR으로도 잘 동작할 것 같습니다.
