### ISSUE TITLE
[공통] 테스팅 도입 및 환경 설정

### ISSUE THREAD

**Issue by gitul0515** [prgrms-web-devcourse/Team-BackFro-ArtZip-FE#333]
# 개요

테스팅에 필요한 `Jest, testing-library` 등의 
라이브러리를 설치하고 기본 환경을 설정합니다. 

# 작업 내용

- [ ] Jest, testing-library 등의 테스팅 라이브러리 설치
- [ ] jest.setup.js, jest.config.js 파일 설정
- [ ] 테스팅이 올바르게 실행되는지 체크

**Comment by punchdrunkard** [comment]
요런 내용도 나중에 정리하실거면 디스커션 기술문서에 남겨주시면 좋겠습니다! (기술을 도입했다면 증거를 남기는게 좋으니깐요 :) )
